# Generated by Django 5.1.3 on 2024-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CLOTHES', 'CLOTHES'), ('ELECTRONICS', 'ELECTRONICS'), ('DEVICES', 'DEVICES')], max_length=100),
        ),
    ]
